# Generated by Django 5.2.5 on 2025-09-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
