# Generated by Django 5.2.5 on 2026-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_category_keywords_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
