# Generated by Django 5.2.5 on 2026-05-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_fetchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchstatus',
            name='is_fetching',
            field=models.BooleanField(default=False),
        ),
    ]
